### ISSUE TITLE
MSL doesn't clean up corrupted .sml files after compilation errors

### ISSUE THREAD

**Issue by Nylux** [DDDDDragon/ModShardLauncher#16]
## Description:

When a mod is compiled to be packed into a `.sml` file, any compilation error leaves behind a corrupted `.sml` file that will make MSL crash on the next start.

## Expected Behavior:

On failed compilations, MSL should remove the newly created `.sml` file to avoid crashing when attempting to read from the Mods folder at the next start.

## Actual Behavior:

MSL leaves behind a corrupted `.sml` file, which leads to a crash on startup.

## Additional Context:
This issue only affects modders, not players.

## Possible Solution:
Error handling should remove the generated `.sml` file in case of compilation error.

**Comment by DDDDDragon** [comment]
that's true
im gonna fix it

**Comment by remyCases** [comment]
Seems properly handled to me
