### ISSUE TITLE
MSL opens an additional console window alongside the actual MSL window

### ISSUE THREAD

**Issue by Nylux** [DDDDDragon/ModShardLauncher#17]
## Description:

Because of the Logger added in  #11, a dedicated console window has appeared.

## Expected Behavior:

The only window should be MSL's.

## Actual Behavior:

A dedicated console window appears alongside MSL's window, and handles the log's output.

## Additional Context:

Never liked @remyCases anyway.

## Possible Solution:
This could be linked to the Logger's default output or a misconfigured `.csproj` ?
@remyCases seems to believe this could also be caused by the tests added in commit da9e5cd ?

**Comment by DDDDDragon** [comment]
this is just a logger, no mistake i think

**Comment by Nylux** [comment]
That's correct, but the logger shouldn't really be shipped in releases ?
It doesn't provide any helpful info for people that just want to install mods, it's only helpful for modders / devs.

I think it should be optional, maybe through UI or something ?

**Comment by DDDDDragon** [comment]
u r right, make a toggle for it maybe a good choice

**Comment by Nylux** [comment]
349f696 added a toggle button, now we just need to use the codebehind to change Serilog's sink ?

Alternatively we can check the state of that checkbox before every Log but uh yeah... not ideal.

**Comment by DDDDDragon** [comment]
Has done it
