### ISSUE TITLE
Logger doesn't log crashes

### ISSUE THREAD

**Issue by Nylux** [DDDDDragon/ModShardLauncher#18]
## Description:

When patching a mod into the `.win` file, if the compilation causes a crash of MSL, the logger doesn't log it.

## Expected Behavior:

The logger should flush the log in the `log.txt` file before MSL crashes.

## Actual Behavior:

The logger fails to log the crash which leads to the inability to understand the reason why MSL crashed.

## Additional Context:

N/A

## Possible Solution:

N/A

**Comment by remyCases** [comment]
Should be partially done now (even done I hope)

**Comment by Nylux** [comment]
Closing for now, reopen if it happens again
