### ISSUE TITLE
ModLoader.GetDecompiledCode Returns Incorrect Function for Overlapping Names

### ISSUE THREAD

**Issue by Nylux** [DDDDDragon/ModShardLauncher#2]
### Title: 
Bug: ModLoader.GetDecompiledCode Returns Incorrect Function for Overlapping Names

### Description:
When calling `ModLoader.GetDecompiledCode` with a function name that overlaps with another function name (e.g., `gml_GlobalScript_scr_village_reputation_add` and `gml_GlobalScript_scr_village_reputation_add_with_log`), the method can return the wrong function.
For exemple the call : 
`ModLoader.InsertDecompiledCode(ModFiles.GetCode("test.gml"), "gml_GlobalScript_scr_village_reputation_add", 0);`
inserts the content of test.gml to gml_GlobalScript_scr_village_reputation_add_with_log rather than the intended gml_GlobalScript_scr_village_reputation_add function.

### Expected Behavior:
`ModLoader.GetDecompiledCode` should return the correct function corresponding to the provided name, even when function names overlap.

### Actual Behavior:
`ModLoader.GetDecompiledCode` returns the first hit which can be a function with a similar name when there are multiple functions with overlapping names.

### Additional Context:
This issue occurs when there are multiple functions with overlapping names.

### Possible Solution:
A possible solution could involve updating the `GetDecompiledCode` method to accurately match the entire function name, rather than returning the first instance of a function that matches the name.

**Comment by DDDDDragon** [comment]
ok thx
will update soon

**Comment by Nylux** [comment]
Should be closed by #6
