### ISSUE TITLE
.win Hook Broken

### ISSUE THREAD

**Issue by Nylux** [DDDDDragon/ModShardLauncher#41]
The hook added by the extension is currently broken.
This means mods' code cannot be loaded in-game.

MSL still works properly, as it compiles into proper `.sml` and `.win` files respectively, but the resulting `.win` doesn't start the Script Engine, which in turn doesn't load the mods code.

**Comment by DDDDDragon** [comment]
actually we dont need script engine to load code in game, the script engine is just like a console to type some command
so we can delete ModShard.dll and the extension now (no need to explain why players need to place the ModShard.dll any more!
Hooray！

**Comment by Nylux** [comment]
Have you tried testing it ?
I can't seem to get it to have any effect in-game, when the exact same mod works fine in previous releases.

**Comment by Nylux** [comment]
Actually was the mod used for testing being broken, skill issue on my end I guess.
