### ISSUE TITLE
Map generation tile mapping broken

### ISSUE THREAD

**Issue by Nylux** [DDDDDragon/ModShardLauncher#44]
## Description:

When walking out of Osbrook while following the road, the next generated map will not have a road, despite the fact that it should.

## Expected Behavior:

Following the road out of Osbrook should always lead to a map which contains a road.

## Additional Context:

A commit after the 0.9.0.0 release seems to have broken this, as the release doesn't seem to be affected.
At this moment, replicating this isn't possible, as some people are experiencing the issue, and others not at all.

## Possible Solution:

N/A, needs more investigation to identify causes.

**Comment by Nylux** [comment]
Seems to not affect the `0.9.0.0` release nor the main branch of MSL as of d54dbab.

**Comment by remyCases** [comment]
Fix in [e825c33b0fd9c7432b74bb2c6ef25ba951de1435](https://github.com/DDDDDragon/ModShardLauncher/commit/e825c33b0fd9c7432b74bb2c6ef25ba951de1435). The culprit seems to be Mods/ModInterfaceEngine.cs. More testing should be done to find the root of this strange issue
